name = "snaptik-bot"
main = "build/worker/shim.mjs"
compatibility_date = "2022-01-20"

[vars]
WORKERS_RS_VERSION = "1.1.0"

[build]
command = "cargo install -q worker-build --version 0.0.7 && worker-build --release"
