name: CI
on: [push]
jobs:
  build:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npx wrangler publish --dry-run --outdir=dist
